---
title: "Data Analysis Report using MIDAS authoring tool"
output: html_document
always_allow_html: yes
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




#Pretreatment of data:

<!-- What are the dimensions of the dataset entering this phase of analysis?-->

<!-- What percentage of the data is Missing Values?-->

<!-- Is imputation performed?-->

<!-- If yes describe method-->

<!-- Is normalisation performed?-->

<!-- If yes describe method-->

<!-- Is transformation performed?-->

<!-- If yes describe method-->

<!-- Is scaling performed?-->

<!-- If yes describe method-->

<!-- Is filtering applied to the dataset at this point?-->

<!-- If yes describe method-->

<!-- Is a QC method employed on the dataset-->

<!-- Please describe-->

<!-- Outline the order of the steps performed on the dataset: E.g. I-> T-> S->N->F->QC-->

<!--Have the dimensions of the dataset changed? If yes how and why?-->

<!--Provide the dimensions of the dataset at the end of the pretreatment phase.-->


<!--Provide details on the package or program used for this phase of the analysis-->

<!--If in house code is used provide it or a link to it and also the language it is written in.-->

<!---->



#Univariate Data Analysis

<!--What are the dimensions of the dataset entering this phase of analysis?-->

<!--Is univariate testing performed?-->

<!--If yes describe method-->

<!--Is multiple testing correction employed with this method?-->

<!--If yes describe method-->

<!--Is another method of univariate testing performed?-->

<!--If yes describe method

<!--Is multiple testing correction employed with this method?

<!--If yes describe method-->

<!--Pleasre report p-values and adjusted p-values.-->

<!--Please report test statistics and confidence intervals.-->

<!--Have the dimensions of the dataset changed? If yes how and why?-->

<!--Provide the dimensions of the dataset at the end of univariate analysis.-->

<!--Provide details on the package or program used for this phase of the analysis-->

<!--If in house code is used provide it or a link to it and also the language it is written in.-->


#Multivariate Data Analysis

<!--What are the dimensions of the dataset entering this phase (Nxm)?-->

<!--Is a data analysis package used?-->

<!--If yes please reference it.-->

<!--Is original code used?-->

<!--If yes please provide a reference link to it.-->


#Unsupervised Analysis

<!--What are the dimensions of the dataset entering this phase of the analysis?-->


<!--Are unsupervised methods employed for visualisation and/ or data reduction and/or correlation analysis?-->

<!--If yes describe method.-->

<!--Are unsupervised analysis methods used for clustering.-->

<!--If yes describe and provide distance metric.-->

<!--Have the dimensions of the dataset changed at the end of this step? If yes, how and why?-->

<!--Provide the dimensions of the dataset at the end of unsupervised analysis.-->

<!--Provide details on the package or program used for this phase of the analysis-->

<!--If in house code is used provide it or a link to it and also the language it is written in.-->

#Supervised Analysis

<!--What are the dimensions of the dataset at this point?-->

<!--Are supervised methods employed?.-->

<!--If yes describe the supervised analysis described fully enough to allow imitation of the exact procedure. This  would require reporting all the following information: all parameters; details of how data is split; details of how internal validation is conducted (i.e. Cross Validation); details of how meta-parameter optimization is performed; details about the chosen metric for assessing the predictive ability of the model and finally the overall description of the workflow.-->

<!--Is more than one supervised method employed?-->

<!--If yes describe the implemention of the other alorithm(s) fully enough to allow imitation of the exact procedure. This  would require reporting all the following information: all parameters; details of how data is split; details of how internal validation is conducted (i.e. Cross Validation); details of how meta-parameter optimization is performed; details about the chosen metric for assessing the predictive ability of the model and finally the overall description of the workflow-->

<!--Is external validation employed?.-->

<!--If yes describe source of external data. Is the data from the same location/ lab/timeline?.-->

<!--Provide a confusion matrix of results..-->

<!--Are potential biomarkers identified? If yes, list them.-->

<!--Have the dimensions of the dataset changed? If yes how and why?-->

<!--Provide the dimensions of the dataset at the end of supervised analysis.-->

<!--Provide details on the package or program used for this phase of the analysis-->

<!--If in house code is used provide it or a link 
to it and also the language it is written in.-->

<!--Describe their performance in terms of AUC, sensitivity and specificity.-->

#ROC Analysis

<!--Is ROC analysis performed on the identified putative biomarkers?-->

<!--If yes please report on AUC sensitivity and specificity-->

<!--Provide details on the package or program used for this phase of the analysis-->

<!--If in house code is used provide it or a link to it and also the language it is written in.-->







```{r include=FALSE}
 library("DiagrammeR")

```



#Workflow Diagram of Pretreatment Phase of Data Analysis
<!--Below you will be instructed to enter the steps of the pretreatment phase of analysis so that they will become nodes of your workflow diagram. You will also be asked to differentiate between the different datasets at each point -->

```{r pressure, echo=FALSE}
grViz("
  digraph boxes_and_circles{
  


  node [shape = box]
###Instruction 1: write out all steps of pretreatment in your analysis as below separated by semicolon, delete or add to this list as appropriate

  Imputation; Normalisation; Scaling; Filtering; QC_Treatment;

  node [shape =  circle]

### Instruction 2: Write out all datasets inputs and outputs and all biomarker lists created at the pretreatment stage, include the dimensions of the input and output datasets in the name, in the following format...dataset#_NxM, where # is the unique identifier of the dataset which is the input or output at that point in the analysis, where N is the number of samples (rows) in the dataset and where m is the number of variables or peaks (columns) in the dataset at that point in the analysis. Delete or add to this list as appropriate


  Dataset1_15x4000; Dataset2_100x3500; BiomarkerList1;
 
### Connect all nodes of the workflow diagram including the dataset inputs and outputs as steps in the diagram, as below 

Dataset1_15x4000->QC_Treatment; 

QC_Treatment-> Dataset2_100x3500; 

Dataset2_100x3500->Imputation; 

Imputation->Normalisation; 

Normalisation->Scaling;

Scaling->Filtering; 

Filtering-> Dataset3_100x1500; 

Filtering->BiomarkerList1;







  }
      ")

```

#Workflow Diagram of all major steps of the Data Analysis




```{r  echo=FALSE}
grViz("
  digraph boxes_and_circles{

### Instruction 3: Write out all steps of the analysis as below separated by semicolon

node [shape = box]


Pretreatment; Univariate_Analysis; Supervised_Analysis; Unsupervised_Analysis;ROC_Analysis;

### Instruction 4: Write out all datasets inputs and outputs and all biomarker lists created at the pretreatment stage, include the dimensions of the input and output datasets in the name, in the following format...dataset#_NxM, where # is the unique identifier of the dataset which is the input or output at that point in the analysis, where N is the number of samples (rows) in the dataset and where m is the number of variables or peaks (columns) in the dataset at that point in the analysis. Delete or add to this list as appropriate

node [shape = circle]

Dataset1_100x4000;  BiomarkerList1; Dataset3_100x1500; BiomarkerList2; BiomarkerList3;  Dataset4;Dataset2_100x3500;

###Connect the nodes with edges

Dataset1_100x4000 ->QC_Treatment;

QC_Treatment-> Dataset2_100x3500; 

Dataset2_100x3500 -> Pretreatment;

Pretreatment ->BiomarkerList1;

Pretreatment ->Dataset3_100x1500;

Dataset3_100x1500-> Univariate_Analysis;

Univariate_Analysis-> BiomarkerList2;

Univariate_Analysis-> Dataset4;

Dataset4->Unsupervised_Analysis;

Dataset4->Supervised_Analysis;

Supervised_Analysis-> BiomarkerList3;

BiomarkerList3-> ROC_Analysis;



  }
      ")

```


```{r  echo=FALSE}
grViz("
  digraph boxes_and_circles{

###Instruction 3: write out all steps of the analysis as below separated by semicolon

node [shape = box]


Pretreatment; Univariate_Analysis; Supervised_Analysis; Unsupervised_Analysis;ROC_Analysis;


node [shape = circle]

Dataset1;  BiomarkerList1; Dataset2; BiomarkerList2; BiomarkerList3;  Dataset3;

###Connect the nodes with edges

Dataset1->Pretreatment;

QC_Treatment-> Dataset2_100x3500; 

Pretreatment ->Dataset2;

Pretreatment ->BiomarkerList1;

Dataset2-> Univariate_Analysis;

Univariate_Analysis-> BiomarkerList2;

Univariate_Analysis-> Dataset3;

Dataset3->Unsupervised_Analysis;

Dataset3->Supervised_Analysis;

Supervised_Analysis-> BiomarkerList3;

BiomarkerList3-> ROC_Analysis;



  }
      ")

```


```{r  echo=FALSE}
grViz("
  digraph boxes_and_circles{

### write out all steps of the analysis as below separated by semicolon

node [shape = box]


Pretreatment; Univariate_Analysis; Supervised_Analysis; Unsupervised_Analysis;ROC_Analysis;


node [shape = circle]

BiomarkerList1; BiomarkerList2; 

###Connect the nodes with edges



Pretreatment ->Univariate_Analysis;

Pretreatment ->Unsupervised_Analysis;

Unsupervised_Analysis->BiomarkerList3;

Unsupervised_Analysis->Univariate_Analysis;

Unsupervised_Analysis ->Supervised_Analysis;

Pretreatment ->Supervised_Analysis;

Univariate_Analysis-> Supervised_Analysis;

Supervised_Analysis->Univariate_Analysis;

Univariate_Analysis->BiomarkerList1;

Supervised_Analysis-> BiomarkerList2;

BiomarkerList2-> ROC_Analysis;

BiomarkerList1-> ROC_Analysis;

  }
      ")

```

